networks:
  internal-network:

services:
  events_db:
    container_name: jornal_db
    image: postgres:14
    environment:
      POSTGRES_DB: jornal_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - internal-network
    ports:
      - "4002:5432"
    volumes:
      - ./jornal_backup.sql:/docker-entrypoint-initdb.d/jornal_backup.sql

volumes:
  pgdata: {}
