networks:
  internal-network:

services:
  events_db:
    container_name: jornal_db
    image: postgres:14
    environment:
      POSTGRES_DB: jornal_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - internal-network
    ports:
      - "4002:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: { }